/* =============================================================================
   ImpactMojo — Theories of Development: the layered causal diagram.

   Each theory is a graph whose nodes belong to exactly one layer and whose
   edges run forward, except for edges the data marks "feedback", which loop
   back to an earlier layer and are drawn dashed and routed around the side.
   The page reveals the layers one at a time, so the reader watches the argument
   being assembled rather than meeting it finished.

   Why the SVG is built here rather than rendered ahead of time: a pre-rendered
   diagram carries its fills baked in, and this site has two themes. Every fill
   and every ink below comes from a CSS custom property defined per theme in
   css/theories.css, so dark mode is a stylesheet concern and the contrast can
   be checked by reading the tokens. rules/testing.md item 12 is the record of
   what happens when ink is chosen at render time instead.

   Data: window.THEORIES, generated by scripts/build-theories.py.
   The theory to draw is named in this script tag's data-theory attribute.
   ============================================================================= */

(function () {
  "use strict";

  var SVG_NS = "http://www.w3.org/2000/svg";

  // Layout constants. Char width is an estimate for the 12.5px bold heading
  // face; it only has to be close, since the box is padded either way.
  var CHAR_W = 7.0, LINE_H = 15, PAD_X = 14, PAD_Y = 11;
  var MIN_NODE_W = 96, COL_GAP = 26, LAYER_GAP = 58, MARGIN = 16, FEEDBACK_LANE = 46;

  function el(name, attrs) {
    var node = document.createElementNS(SVG_NS, name);
    for (var k in attrs) if (attrs.hasOwnProperty(k)) node.setAttribute(k, attrs[k]);
    return node;
  }

  function measure(node) {
    var lines = String(node.label).split("\n");
    var widest = 0;
    for (var i = 0; i < lines.length; i++) widest = Math.max(widest, lines[i].length);
    return {
      lines: lines,
      w: Math.max(MIN_NODE_W, Math.round(widest * CHAR_W) + PAD_X * 2),
      h: lines.length * LINE_H + PAD_Y * 2
    };
  }

  /* Assign coordinates. Within a layer, nodes are ordered by the average x of
     the nodes that point into them, which is the standard barycentre pass and
     is enough to keep the arrows from crossing on graphs this size. */
  function layout(theory) {
    var placed = {}, layers = [], edges = [], y = MARGIN, maxW = 0;

    theory.layers.forEach(function (layer, li) {
      (layer.edges || []).forEach(function (e) {
        edges.push({ from: e[0], to: e[1], label: (e.length > 2 && e[2] !== "feedback") ? e[2] : "",
                     feedback: e.length > 2 && e[2] === "feedback", layer: li });
      });
    });

    theory.layers.forEach(function (layer, li) {
      var boxes = layer.nodes.map(function (n) {
        var m = measure(n);
        return { id: n.id, kind: n.kind, lines: m.lines, w: m.w, h: m.h, layer: li };
      });

      if (li > 0) {
        boxes.forEach(function (b) {
          var xs = edges.filter(function (e) { return e.to === b.id && placed[e.from]; })
                        .map(function (e) { return placed[e.from].x + placed[e.from].w / 2; });
          b._bary = xs.length ? xs.reduce(function (a, v) { return a + v; }, 0) / xs.length : Infinity;
        });
        boxes.sort(function (a, b) { return a._bary - b._bary; });
      }

      var rowW = boxes.reduce(function (a, b) { return a + b.w; }, 0) + COL_GAP * (boxes.length - 1);
      var rowH = boxes.reduce(function (a, b) { return Math.max(a, b.h); }, 0);
      layers.push({ y: y, h: rowH, w: rowW, boxes: boxes });
      maxW = Math.max(maxW, rowW);
      y += rowH + LAYER_GAP;
    });

    // Centre every row against the widest one, then record final positions.
    layers.forEach(function (row) {
      var x = MARGIN + (maxW - row.w) / 2;
      row.boxes.forEach(function (b) {
        b.x = x; b.y = row.y + (row.h - b.h) / 2;
        placed[b.id] = b;
        x += b.w + COL_GAP;
      });
    });

    var hasFeedback = edges.some(function (e) { return e.feedback; });
    return {
      nodes: placed,
      layers: layers,
      edges: edges,
      width: maxW + MARGIN * 2 + (hasFeedback ? FEEDBACK_LANE : 0),
      height: y - LAYER_GAP + MARGIN,
      lane: maxW + MARGIN + FEEDBACK_LANE * 0.62
    };
  }

  function edgePath(g, a, b) {
    var x1 = a.x + a.w / 2, y1 = a.y + a.h;
    var x2 = b.x + b.w / 2, y2 = b.y;
    var dy = Math.max(18, (y2 - y1) * 0.5);
    return "M" + x1 + "," + y1 + " C" + x1 + "," + (y1 + dy) + " " + x2 + "," + (y2 - dy) + " " + x2 + "," + y2;
  }

  /* A feedback edge runs the wrong way down the page, so it leaves the right
     edge of its source, travels up a reserved lane and comes back in on the
     right edge of its target. Drawing it as a plain bezier would put it
     straight through the boxes in between. */
  function feedbackPath(g, a, b) {
    var x1 = a.x + a.w, y1 = a.y + a.h / 2;
    var x2 = b.x + b.w, y2 = b.y + b.h / 2;
    var lane = g.lane;
    return "M" + x1 + "," + y1 + " C" + lane + "," + y1 + " " + lane + "," + y2 + " " + x2 + "," + y2;
  }

  function render(container, theory) {
    var g = layout(theory);
    var svg = el("svg", {
      viewBox: "0 0 " + Math.round(g.width) + " " + Math.round(g.height),
      preserveAspectRatio: "xMidYMin meet", role: "img",
      // The accessible name is the step's own heading and paragraph, which
      // change as the reader advances. axe reports role="img" with no name as
      // a serious failure, and it is right: without this the diagram is an
      // unlabelled graphic to a screen reader.
      "aria-labelledby": "dgTitle dgText"
    });

    var defs = el("defs");
    var marker = el("marker", { id: "th-arrow", viewBox: "0 0 10 10", refX: "9", refY: "5",
                                markerWidth: "6", markerHeight: "6", orient: "auto-start-reverse" });
    marker.appendChild(el("path", { d: "M 0 0 L 10 5 L 0 10 z", "class": "th-arrowhead" }));
    defs.appendChild(marker);
    svg.appendChild(defs);

    var edgeLayer = el("g", { "class": "th-edges" });
    var nodeLayer = el("g", { "class": "th-nodes" });
    svg.appendChild(edgeLayer);
    svg.appendChild(nodeLayer);

    var edgeEls = [], nodeEls = [];

    g.edges.forEach(function (e) {
      var a = g.nodes[e.from], b = g.nodes[e.to];
      if (!a || !b) return;   // the build script rejects this; belt and braces.
      var wrap = el("g", { "class": "th-edge-group th-hidden" });
      var cls = "th-edge" + (e.feedback ? " th-edge--feedback" : "");
      wrap.appendChild(el("path", {
        "class": cls, "marker-end": "url(#th-arrow)",
        d: e.feedback ? feedbackPath(g, a, b) : edgePath(g, a, b)
      }));
      edgeLayer.appendChild(wrap);
      edgeEls.push({ node: wrap, layer: Math.max(a.layer, b.layer) });
    });

    Object.keys(g.nodes).forEach(function (id) {
      var b = g.nodes[id];
      var wrap = el("g", { "class": "th-node th-node--" + b.kind + " th-hidden" });
      wrap.appendChild(el("rect", { x: b.x, y: b.y, width: b.w, height: b.h, rx: 10, ry: 10 }));
      var text = el("text", {
        x: b.x + b.w / 2, y: b.y + PAD_Y + LINE_H * 0.72,
        "text-anchor": "middle"
      });
      b.lines.forEach(function (line, i) {
        var tspan = el("tspan", { x: b.x + b.w / 2, dy: i === 0 ? 0 : LINE_H });
        tspan.textContent = line;
        text.appendChild(tspan);
      });
      wrap.appendChild(text);
      var title = el("title");
      title.textContent = b.lines.join(" ");
      wrap.appendChild(title);
      nodeLayer.appendChild(wrap);
      nodeEls.push({ node: wrap, layer: b.layer });
    });

    container.innerHTML = "";
    container.appendChild(svg);

    /* Two decisions worth stating. Earlier steps stay readable rather than
       fading almost out: the point of building the chain up is that the
       reader can still see what it was built from, so the current step is
       marked with a stroke instead. And the viewBox grows downward with the
       diagram, so step one is not a mostly empty box with the argument's
       eventual height reserved in advance. */
    return function show(step) {           // step is 1-based
      var bottom = MARGIN;
      nodeEls.concat(edgeEls).forEach(function (item) {
        var visible = item.layer <= step - 1;
        item.node.classList.toggle("th-hidden", !visible);
        item.node.classList.toggle("th-past", visible && item.layer < step - 1);
        item.node.classList.toggle("th-current", visible && item.layer === step - 1);
      });
      g.layers.slice(0, step).forEach(function (row) {
        bottom = Math.max(bottom, row.y + row.h);
      });
      svg.setAttribute("viewBox", "0 0 " + Math.round(g.width) + " " + Math.round(bottom + MARGIN));
    };
  }

  function init() {
    var script = document.querySelector("script[data-theory]");
    var canvas = document.getElementById("dgCanvas");
    if (!script || !canvas || !window.THEORIES) return;

    var id = script.getAttribute("data-theory");
    var theory = null;
    window.THEORIES.theories.forEach(function (t) { if (t.id === id) theory = t; });
    if (!theory) return;

    var show = render(canvas, theory);
    var total = theory.layers.length;
    var step = 1;

    var elStep = document.getElementById("dgStep");
    var elTitle = document.getElementById("dgTitle");
    var elText = document.getElementById("dgText");
    var btnBack = document.getElementById("dgBack");
    var btnNext = document.getElementById("dgNext");

    function go(n) {
      step = Math.min(total, Math.max(1, n));
      show(step);
      var layer = theory.layers[step - 1];
      elStep.textContent = "Step " + step + " of " + total;
      elTitle.textContent = layer.title;
      elText.textContent = layer.text;
      btnBack.disabled = step === 1;
      btnNext.disabled = step === total;
      btnNext.textContent = step === total ? "That is the whole argument" : "Next →";
    }

    btnBack.addEventListener("click", function () { go(step - 1); });
    btnNext.addEventListener("click", function () { go(step + 1); });

    document.addEventListener("keydown", function (e) {
      var t = e.target;
      if (t && (t.tagName === "INPUT" || t.tagName === "TEXTAREA" || t.isContentEditable)) return;
      if (e.key === "ArrowRight") { e.preventDefault(); go(step + 1); }
      if (e.key === "ArrowLeft") { e.preventDefault(); go(step - 1); }
    });

    go(1);
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
